version: '3.3'

services:
  backend:
    build: .
    command: ["npm", "run", "dev"]
    ports:
      - "8080:8080"
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      - NODE_ENV=development
    env_file:
      - ./secrets.env

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=http://backend/api
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - "./frontend:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3000"
